- name: Download kubeadm from storage.googleapis.com
  hosts: haproxy
  tasks:
   - name: Downloading kubectl
     become: yes
     get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/kubectl
        dest: '/usr/local/bin/'
        mode: '+x'

   - name: Downloading kubeadm
     become: yes
     get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/kubeadm
        dest: '{{ DOWNLOAD_DIR }}'
        mode: '+x'
     delegate_to: master01

   - name: Downloading kubelet
     become: yes
     shell: |
       sudo kubeadm upgrade apply {{ RELEASE }}
       sudo kubeadm upgrade node
       sudo kubeadm upgrade apply
     delegate_to: master01

- name: Download kubeadm from storage.googleapis.com
  hosts: kubernetes
  tasks:
   - name: Downloading kubelet
     get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/kubeadm
        dest: '{{ DOWNLOAD_DIR }}'
        mode: '+x'

   - name: Downloading kubelet
     get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/kubectl
        dest: '{{ DOWNLOAD_DIR }}'
        mode: '+x'

   - name: Downloading kubelet
     get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/kubelet
        dest: '{{ DOWNLOAD_DIR }}'
        mode: '+x'

   - name: running sysctl daemon-reload command
     become: yes
     command:
       cmd: systemctl daemon-reload

   - name: running restart kubelet command
     become: yes
     command:
       cmd: systemctl restart kubelet
