---
- name: Install HAProxy
  hosts: haproxy
  become: yes

  tasks:
    - name: Install HAProxy package
      apt:
        name: haproxy
        state: present
      become: yes
      become_method: sudo

    - name: Copy HAProxy configuration file
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Restart HAProxy service
      service:
        name: haproxy
        state: restarted
      become: yes
#---
- name: Install and configure Samba
  hosts: smb-srv
  become: yes
  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present
    - name: Create smb.conf file
      copy:
        content: |
          [file-loader]
              comment = Ubuntu File Server Share
              path = {{ samba-folder }}
              browsable = yes
              guest ok = yes
              read only = no
              create mask = 0755
        dest: "/etc/samba/smb.conf"
      become: true

    - name: Restart Samba
      service:
        name: smbd
        state: restarted
#---
- name: Install NFS server
  hosts: nfs-srv
  become: true
  tasks:
    - name: creating nfs directory
      file:
        path: {{ nfs-folder }}
        owner: nobody
        group: nogroup
        state: directory
        mode: '0755'

    - name: Install NFS packages
      apt:
        name:
          - nfs-kernel-server
          - nfs-common
        state: present

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "{{ item }}"
        state: present
      with_items:
        - "{{ nfs-folder }} {{ subnet }}(rw,sync,no_subtree_check)"
      notify:
        - Restart NFS server

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted
